In [ ]:
import numpy as np

: 

### Cumsum

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7]);
print(arr)

print(np.cumsum(arr))

### Concatenate

In [ ]:
arr1 = np.array([4 ,5 , 7 , 8])
arr2 = np.array([4,6,8,6,6])
arr3 = np.concatenate((arr1,arr2))
print(arr3)

### hstack

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

res = np.hstack((a,b))
print(res)

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(a)
print()
print(b)

res = np.hstack((a, b))
print()
print(res)

### Vstack

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(a)
print()
print(b)

res = np.vstack((a, b))
print()
print(res)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### Split

In [ ]:
a = np.arange(0, 10)
print(a)

result = np.split(a, 2)
print(result)



[0 1 2 3 4 5 6 7 8 9]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


### Insert 

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
np.insert(a, 3, 7)
print(a)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
